# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f46941770bb5177780e854cd1767edc6d9110c1d78bff29d8ce2caf9e2012cbdb13466e72862d08672bb401e4ca3f0118b6d7ac9e7cd367c3151df78906df610

test:
  secret_key_base: 305565f9700893ac89c29b388b7aa3921115651dfffca4e1ce3c1b9517a2d2413836ff4b64cacc6e985fddefd013a2e6e8fa7f4e309046959cbcffc17c11e8e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
